acc_it: 1
anomaly_ratio: 1.0
batch_size: 32
checkpoints: ./checkpoints/
clip_grad: null
d_model: 512
data: All
debug: enabled
des: test
dist_url: env://
dropout: 0.1
e_layers: 2
features: M
fix_seed: null
freq: h
inverse: false
is_training: 1
itr: 1
large_model: true
layer_decay: null
learning_rate: 0.0001
local-rank: null
lradj: supervised
mask_rate: 0.25
max_offset: 0
memory_check: true
min_lr: null
model: UniTS
model_id: test
n_heads: 8
num_workers: 0
offset: 0
patch_len: 64
pretrained_weight: null
project_name: tsfm-multitask
prompt_num: 5
prompt_tune_epoch: 0
share_embedding: false
stride: 64
subsample_pct: null
target: OT
task_data_config_path: data/task_data_yaml/multi_task.yaml
task_name: ALL_task
train_epochs: 10
warmup_epochs: 0
weight_decay: 0.0
zero_shot_forecasting_new_length: null
