# model


# 1 task
itr: 1
name: test
# 2 exp 
## 2.1 setting


seed: 17
is_training: 1
acc_it: 1
exp_num: 1
device: cuda
seed: 17
name: "dummy_exp"
gpus: 1
# debug: True


## 2.2 dirs

save_dir: ./save
checkpoints: ./checkpoints/
name: test

## 2.3 hyperparameters

learning_rate: 0.0001
batch_size: 64
num_epochs: 300
weight_decay: 0.0001

## 2.4 training

mask_rate: 0.25
train_epochs: 10
warmup_epochs: 0
patience: 100
num_epochs: 300

# 3 data_task

## data
num_workers: 32
## task 
task_name: ALL_task
# 4 model

## 4.1 model_setting

d_model: 512
dropout: 0.1
e_layers: 2
large_model: true
patch_len: 64
stride: 64
prompt_num: 5

# 5 wandb
wandb_flag: True
task_name: "dummy_task"
model: Sparse_Fre_Transformer
data: dummy_data
monitor: val_loss  # ???
scheduler: ReduceLROnPlateau
run_mode: offline # online offline disabled