# model


# 1 task


# 2 exp 
## 2.1 setting

exp_num: 1
device: cuda
seed: 17
name: "dummy_exp"
gpus: 1
debug: True

## 2.2 dirs

save_dir: ./save

## 2.3 hyperparameters

learning_rate: 0.0001
batch_size: 64
num_epochs: 300
weight_decay: 0.0001



# 3 data

num_works: 32

# 4 model

## 4.1 


# 5 wandb
wandb_flag: True
task_name: "dummy_task"
model: SFT
data: dummy_data